# DEVELOPMENT docker-compose.yml

services:
  nodejs:
    image: node:18.18.2-alpine3.18
    working_dir: /app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ".:/app:rw"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    command: [ "yarn", "docker-dev" ]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres"
    attach: false
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data: