services:
  web:
    image: unit_endpoints
    container_name: unit_endpoints
    ports:
      - target: 8000
        published: 8000
    environment:
      DISABLE_NEST_ASYNCIO: True
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_ADDRESS: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres"
    container_name: unit_db
    volumes:
      - unit:/home/postgres_data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}

volumes:
  unit: