POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "email@mail.ru",
  "password": "wtf"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "email@mail.ru",
  "name": "Test",
  "phone": "+121273821",
  "password": "wtf"
}

###
